# Generated by Django 2.2 on 2019-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='imageID',
            field=models.IntegerField(default=0),
        ),
    ]
